GET http://localhost:4000/api/admin
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzM0MzI4NTc2LCJleHAiOjE3MzQ0MTQ5NzZ9.L31QmgwpsyvIqzvT8d5Ctr2xNrO3gWkFFAoReO7CpFQ
